- name: Fleetctl - Destroy all instances
  shell: fleetctl destroy /home/core/services/instances/*
  tags:
    - update
    - restart-all
    - destroy
    - lb

- name: Fleetctl - Destroy all templates
  shell: fleetctl destroy /home/core/services/templates/*
  tags:
    - update
    - restart-all
    - destroy
    - as

- name: Fleetctl - Submit all templates
  shell: fleetctl submit /home/core/services/templates/*
  tags:
    - update
    - restart-all
    - as

# - name: Fleetctl - Submit all instances
#   shell: fleetctl submit /home/core/services/instances/*
#   tags:
#     - update
#     - restart-all
#     - lb

# - name: Fleetctl - Start all instances
#   shell: fleetctl start /home/core/services/instances/*
#   tags:
#     - update
#     - restart-all
#     - lb